# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3.11
    -   id: end-of-file-fixer
        language_version: python3.11
    -   id: check-yaml
        language_version: python3.11
    -   id: check-added-large-files
        language_version: python3.11
    -   id: check-json
        language_version: python3.11
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.7
  hooks:
    - id: ruff
      args: ["--fix"]
      language_version: python3.11
      files: src
    - id: ruff-format
      language_version: python3.11
      files: src
    - id: ruff
      language_version: python3.11
      files: src
