steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'us-central1-docker.pkg.dev/starfish-detection/registry/train',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'us-central1-docker.pkg.dev/starfish-detection/registry/train'
  ]
options:
  env:
    - DOCKER_BUILDKIT=1
  logging: CLOUD_LOGGING_ONLY
