site_name: Starfish Detection
site_author: Group 36
# docs_dir: source

theme:
    language: en
    name: material
    features:
    - content.code.copy
    - content.code.annotate

plugins:
    - search
    - mkdocstrings

nav:
  - Home: index.md
