_target_: starfish.model.FasterRCNNLightning
num_classes: 2
log_ap: true
learning_rate: 0.001
momentum: 0.9
weight_decay: 0.0005

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 3
  gamma: 0.1

compile: false
