_target_: starfish.model.FasterRCNNLightning
num_classes: 2
log_ap: true

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 3
  gamma: 0.1

compile: false
