# sweep_config.yaml
method: bayes
program: src/starfish/train.py
metric:
  name: val_total_loss
  goal: minimize
parameters:
  model.optimizer.lr:
    distribution: uniform
    min: 0.00001
    max: 0.01
  model.optimizer.weight_decay:
    distribution: uniform
    min: 0
    max: 0.01
command:
  - python
  - ${program}
  - ${args_no_hyphens}
project: 'Starfish Detection'
entity: luciagordon-harvard-university
run_cap: 5
