# sweep_config.yaml
method: bayes
program: src/starfish/train.py
metric:
  name: val_total_loss
  goal: minimize
parameters:
  model.optimizer.lr:
    distribution: uniform
    min: 0.00001
    max: 1
  model.optimizer.momentum:
    distribution: uniform
    min: 0
    max: 1
command:
  - python
  - ${program}
  - ${args_no_hyphens}
  - data.data_from_bucket=false
  - trainer.max_epochs=1
project: 'Starfish Detection'
entity: luciagordon-harvard-university
run_cap: 5
