workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: us-central1-docker.pkg.dev/starfish-detection/registry/train
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY