workerPoolSpecs:
    machineSpec:
        # machineType: n1-highmem-2
        machineType: a2-highgpu-1g
        acceleratorType: NVIDIA_TESLA_A100
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: us-central1-docker.pkg.dev/starfish-detection/registry/train
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
