_wandb:
    value:
        cli_version: 0.19.2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 80
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 80
                - 103
                - 105
            "3":
                - 7
                - 15
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
