name: DVC Workflow

on:
  push:
    branches:
    - master
    paths:
    - '**/*.dvc'
    - '.dvc/**'

jobs:
  print-update-message:
    name: Print Update Message
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print message
      run: echo "Data has been updated"
